### ISSUE TITLE
Will it plan to support mobile platform?

### ISSUE THREAD

**Issue by ajeecai** [aarzilli/nucular#10]
Hi,

It is great to see so nice GUI with pure go, in a relatively simple code base. Is there any example using it on mobile (IOS/Andriod) platform? gomobile should have this support but I am so new a gopher that I can't do it by myself. 

Thanks

**Comment by aarzilli** [comment]
If shiny is ported to gomobile nucular will work there.

**Comment by ajeecai** [comment]
As  I know, x/shiny is parallel with x/mobile so it is not expected that shiny ported to gomobile? I saw some project like https://github.com/dskinner/material can build desktop app and also mobile version,  does it have something that we can learn from?

**Comment by dskinner** [comment]
Given shiny just draws to an image.RGBA, pushing that as a texture on any platform is possible with some bootstrapping. I have an example of this in my x/glw repo I need to push.

**Comment by ajeecai** [comment]
Thanks dskinner. Hi @aarzilli is this in you plan? For some of my purposes I wish to have one GUI widget based app for all platforms (Windows/Linux/Mac/IOS/iPhone), searching github can't find any available respo. I hope  I can help but currently I am not good at go while I just try to learn ...

**Comment by ajeecai** [comment]
Thanks dskinner. Hi @aarzilli is this in you plan? For some of my purposes I wish to have one GUI widget based app for all platforms (Windows/Linux/Mac/IOS/iPhone), searching github can't find any available respo. I hope  I can help but currently I am not good at go while I just try to learn ...

**Comment by aarzilli** [comment]
I don't have a plan, I don't take feature requests unaccompained by a pull request for this project. If porting to android becomes easy enough I might but I have no timeline for that.
