### ISSUE TITLE
window resize speed

### ISSUE THREAD

**Issue by joeblew99** [aarzilli/nucular#2]
works perfect on windows 10

is super slow catching up on osx 12.10

**Comment by aarzilli** [comment]
I don't have the ability to test this library on OS X so I can not help you with this.

**Comment by joeblew99** [comment]
do you want it fixed ? A PR ?

**Comment by aarzilli** [comment]
Sure!

**Comment by joeblew99** [comment]
OK . was quick.

I will leave this open, and investigate a fix.

If you have any ideas let me know...

**Comment by aarzilli** [comment]
In the overview demo if you press ctrl+f it will print the framerate in the bottom right of the window, maybe it's too slow to keep up with the resizes for some reason. In any case the problem is in shiny.go.

**Comment by joeblew99** [comment]
thats helpful..

Let me have a go now...

**Comment by joeblew99** [comment]
i just a git pull, and recompiled the _demo, but cant get the framerate showing..
Any ideas ???

**Comment by aarzilli** [comment]
I pushed a commit, do another pull. Note that the fps indicator will only show up after a redraw, try interacting with the window. If it still doesn't show it's another bug, could be that shiny is sending a different keycode for ctrl+f on OS X compared to linux.

**Comment by joeblew99** [comment]
ok ta. Will try again...

**Comment by joeblew99** [comment]
Ok got it showing on OSX.
When i press ctrl+f is does not show, but if you then maximise the window it then does show.
Another minor bug for OSX i guess ?

**Comment by joeblew99** [comment]
OSX:
https://www.youtube.com/watch?v=myQNgVCXMlE

**Comment by joeblew99** [comment]
WIN10:
https://www.youtube.com/watch?v=k9LLoAFSFPY

**Comment by joeblew99** [comment]
I am wondering if the framerates are REALLY that different from yours ???
I am running windows10 inside VirtualBox...

**Comment by aarzilli** [comment]
I also run windows 10 in VirtualBox and it's not that different, what's odd is that it's running so slow non-virtualized. 
In general it should drop frames if it can't keep up with a resize but I never got around to implementing that.

**Comment by joeblew99** [comment]
ok thanks

I was thinking about this....When i was using just shiny.go for some play things, and even their examples, resize was really smooth.

https://github.com/golang/exp/blob/master/shiny/example/textedit/main.go
Still lots Shiny needs :)
// TODO: cursors + editing (not just viewing) text, key + mouse events,
// scrolling, load/save, clipboard.

Shiny has gotten some good flex like layout tools lately. 

??
