### ISSUE TITLE
The Chinese becomes a square

### ISSUE THREAD

**Issue by ppmoon** [aarzilli/nucular#22]
![image](https://user-images.githubusercontent.com/3971390/49641146-4cee2700-fa4a-11e8-9212-b42be14376c8.png)
windows 10
What should I do?

**Comment by aarzilli** [comment]
Use a different font. See gdlv's [setupStyle](https://github.com/aarzilli/gdlv/blob/e4a25e3fd8256ccf15fa487a9842d42708a78350/main.go#L59). Basically:

```
style := wnd.Style() // wnd is your MasterWindow
style.Font = truetype.NewFace(...)
```

**Comment by ppmoon** [comment]
Thank you I fixed the problem

**Comment by aarzilli** [comment]
You're welcome.
