### ISSUE TITLE
demo and overview do not compile

### ISSUE THREAD

**Issue by avoll** [aarzilli/nucular#26]
Hi, got the latest source as of 2019-02-25, but getting compile errors - forgot to check in files?

> 
>(base) C:\Dev\go\src\github.com\aarzilli\nucular\_examples\overview>go run main.go
>\# command-line-arguments
>.\main.go:35:8: undefined: newOverviewDemo
>

and 

>
>(base) C:\Dev\go\src\github.com\aarzilli\nucular\_examples\demo>go run demo.go
>\# command-line-arguments
>.\demo.go:57:10: undefined: calcDemo
>.\demo.go:62:9: undefined: newOverviewDemo

Thank you,
Alexander

**Comment by aarzilli** [comment]
See https://github.com/aarzilli/nucular/issues/1#issuecomment-253515939
