### ISSUE TITLE
Closing window on macOS.

### ISSUE THREAD

**Issue by dexter3k** [aarzilli/nucular#27]
Hey.
As mentioned in #25 window can be closed like so:
```golang
func update(w *nucular.Window) {
    w.Row(50).Dynamic(1)
    if w.ButtonText("Close window!") {
        go w.Master().Close()
    }
}
```
This does close main window indeed, but keeps the MasterWindow.Main function looping forever.
Is there any way to completely stop window routine and pass control past call to Main?

Also possibly related: default macOS menubar hotkeys do not seem to trigger when window is open. Do I have to manually provide menubar hotkey checks?

Thanks in advance.

**Comment by aarzilli** [comment]
These seem more like problems with shiny rather than nucular. I don't really know anything about GUI programming on macOS. There seems to be a more maintained version of shiny at github.com/oakmound/shiny, maybe those are already fixed there, you could check with a replace directive.

**Comment by dexter3k** [comment]
Migrating to `github.com/oakmound/shiny` does change things. At least, there is a StageDead event generated when pressing the red X button (which did not happen with the original shiny).

Now the problem is in the `func (mw *masterWindow) main(s screen.Screen)`.

`for` loop keeps waiting for events even when there are no windows open and `mw.closing` is true. Since no windows are open, loop will wait forever and never return control to caller.

It is a problem with shiny and not with nucular and I will file in issue in corresponding repo. But I think there is still a way to fix that on nucular side :)

For example we can `Send` a dummy event to shiny which will result in nucular checking for `mw.closing` flag.

Thanks.

**Comment by aarzilli** [comment]
There's this check in handleEventLocked:

```
		if e.Crosses(lifecycle.StageDead) == lifecycle.CrossOn || e.To == lifecycle.StageDead || w.closing {
			w.closing = true
			w.closeLocked()
			return false
		}
```

If this returns false then the loop in main should exit. If a StageDead event is generated this should happen, why does it not?

**Comment by dexter3k** [comment]
StageDead is generated when OS commands window to close.
If we try to handle user input and programmatically close window, then
```golang
func (w *masterWindow) closeLocked() {
	w.closing = true
	if w.wndb != nil {
		w.wndb.Release()
	}
	w.wnd.Release()
}
```
will set w.closing and call w.wnd.Release(), but it will not send no new events to 
`ei := mw.wnd.NextEvent()`
and it will wait forever as closed window will not receive any new events.

I have no access to other platforms atm (only macOS), but I guess that on other platforms wnd.Release will send a StageDead event.

This is a bug originating from shiny, though it can be fixed from nucular side with (hopefully) no side effects.

For example:
```golang
type closingEvent struct {}

func (w *masterWindow) closeLocked() {
	w.closing = true
	if w.wndb != nil {
		w.wndb.Release()
	}
	w.wnd.Release()
	w.wnd.Send(closingEvent{})
}
```

And in
```golang
func (w *masterWindow) handleEventLocked(ei interface{}) bool
```
we can do

```golang
case closingEvent:
	return !w.closing // or even better - assert that w.closing is always true there
```

**Comment by aarzilli** [comment]
Ok, I get it now. It works when pressing the close button but not if the close is initiated by calling MasterWindow.Close. I think you should report this upstream to shiny. I'd prefer to see it fixed there rather than adding a workaround. If it doesn't get fixed soon you can submit a PR for this workaround and I'll merge it.

**Comment by dexter3k** [comment]
I have just found out that after calling Window.Release() behaviour of window becomes undefined (which is logical given that Go's Release and Destroy methods usually mark objects deleted/abandoned).
This hints that calling Release during a call to NextEvent or calling NextEvent after a call to Release (which might happen sometimes) will lead to undefined behaviour.

My workaround from previous message will also produce undefined behaviour due to the fact that it creates an event after a call to Release.

I.e. we can only call wnd.Release after ending NextEvent for loop in masterWindow.main.
To close window programmatically a some kind of quitEvent struct should be created and handled by returning from event loop.

If you want me to make a pull request, I can do that, but I'm not sure I can migrate to newer shiny without creating a mess in go modules.

**Comment by aarzilli** [comment]
See what you think about this solution.

**Comment by dexter3k** [comment]
Good work, now it does work as intended on macOS and undefined behaviour is removed.

Though red cross button functionality on macOS still requires migration to a newer shiny fork :) Maybe some day in the future 🤔
