### ISSUE TITLE
Why vendor public packages?

### ISSUE THREAD

**Issue by dexter3k** [aarzilli/nucular#30]
Some of my code uses original packages which conflict with nucular's vendored packages.
```golang
go\src\dexter\nucular-pg\update.go:37:26: cannot use "golang.org/x/mobile/event/mouse".ButtonLeft (type "golang.org/x/mobile/event/mouse".Button) as type "github.com/aarzilli/nucular/vendor/golang.org/x/mobile/event/mouse".Button in argument to w.Input().Mouse.Down
```
This requires me to write dummy converters between vendored and non-vendored packages. Which creates mess in the code.

So my question is: is there any adequate reason to vendor packages that are required to interface with the library? I removed vendored packages and replaced them with their newest versions and did not notice any problems.

Thanks.

**Comment by aarzilli** [comment]
Build reproducibility.

**Comment by aarzilli** [comment]
PS. this problem is a known shortcoming of GOPATH, you shouldn't write converters, rather you should use either modules or a dependency manager (dep, govendor, etc...)
