### ISSUE TITLE
nucular.TextEditor does not allow entering certain characters

### ISSUE THREAD

**Issue by waltrapa** [aarzilli/nucular#39]
Code of example:

====== init of code ======
package main

import (
	"github.com/aarzilli/nucular"
	"github.com/aarzilli/nucular/style"
)

var FieldEditor nucular.TextEditor

func main() {
	wnd := nucular.NewMasterWindow(0, "Test", updatefn)
	wnd.SetStyle(style.FromTheme(style.DarkTheme, 2.0))
	wnd.Main()
}

func updatefn(w *nucular.Window) {
	w.Row(20).Dynamic(1)
	FieldEditor.Edit(w)
}
======= end of code ========

No input for char "ñ" or "ç" and others "extra" chars.
Ubuntu Linux 18.04 on amd64.

Thanks.

**Comment by aarzilli** [comment]
See https://go-review.googlesource.com/c/exp/+/171940

**Comment by waltrapa** [comment]
Thank you again.

Fixed extra chars but if press any of keys :
- "Alt Gr."
- "block uppercase"
- "numerical block"
- Any operation symbol key "+ - * /" in numerical block

TextEditor, print a "square".
