### ISSUE TITLE
Platform dependencies, a decline from Nuklear philosophy

### ISSUE THREAD

**Issue by xlab** [aarzilli/nucular#4]
Hello! 

First, thanks for the project, I'm a big fan of using Go outside its server-side niche, and this project
contributes to spread this idea. The Nuklear UI toolkit is an example how to properly design GUI toolkits, it's indeed a good source of inspiration for us, gophers, too.

But what I'm concerned about is the fact that some of crucial Nuklear ideas been ignored in this port, for example, no dependencies on the OS / platform. Nuklear handles UI without relying on the platform implementation, and that's a huge deal. Nucular as opposite, embeds platform integration code within,
makes it harder to port on different platforms. Actually, it relies on `/x/mobile` for platform integration,
the project that is very close to the Go upstream and is very conservative on features and development.

I'm just concerned that even this project develops fast, it will be limited by platform support,
soon or later, so better be thinking about backend decoupling at some nearest future.

(just my thoughts)

**Comment by aarzilli** [comment]
Most of the OS specific code is handled through shiny and integration with shiny is mostly confined to shiny.go. Initially this was relegated into a different package but doing that ended up cluttering (even more) the API and I didn't have a clear use case for it anyway.

Shiny may be conservative (I definitely wish there was a way to change pointer cursors) but it's also further along multiplatform support than anything else in the go ecosystem (at least, that I know of).

Still, nucular's API isn't set in stone, if somebody ends up writing a different backend for nucular I will consider splitting shiny.go to its own package.

**Comment by joeblew99** [comment]
Hey @xlab 


My 2 cents:
https://github.com/vurtun/nuklear
- tried it and is too limited in what you can do with it in terms of GUI styles. that was my issue.
- as a golang programmer i want to make my own GUI styles using as much golang as possible. For example, i want to make a more material designish control lib and add some fragment shaders etc

I love the vulkan work and android / ios work you are doing. Its very needed and i am using it in my projects now.  Just found nuklear a bit too cramped :)

This repo did a decent job of abstraction from what i can see:
https://github.com/hajimehoshi/ebiten/blob/master/internal/opengl/context_mobile.go
- did not use shiny.

https://github.com/hajimehoshi/ebiten/tree/master/internal/opengl
- has decent abstraction for different backends

I am not a great opengl expert. Just wanting to get GUi stuff working for golang :)

**Comment by xlab** [comment]
@joeblew99 Hi!

`<off-topic>`
I understand your pain and would agree that Nuklear provides slightly less stuff out of the box than expected. But having 10+ years in GUI development I'd stay that this problem is very common. Every framework you choose will be cramped in some way, until you start implementing your own widgets and graphics.

The most advanced framework currently is Qt, I wish we could have something like QML+JS but in Go, but it will take 2 man-years in my estimation to accomplish that. Qt has been developed for decades, but major shift has been done in period 2009-2012 when QML and Qt5 were introduced.

They were first (except W3C) who were able to create a set of small orthogonal components to make any UI possible, instead of pre-defined widgets. However, to hide some complexity they created a few widgets and styles, I'm talking about QtQuick and platform-dependent styles.

So thinking about Nuklear as box of defined widgets is wrong (and stating that this box is small for the needs), it's a low-level layer that abstracts away most of GL stuff and adds some helpers which otherwise would be hard to implement. All this layout stuff, scrollable canvases, widgets, drawing, pipelines, font baking etc. And by hard I meant that these problems are complex in terms of math, not just because the documentation may be long to read.

>  repo did a decent job of abstraction from what i can see

Unfortunately I'm bad at telling a bad abstraction from good at the first sight. For example, Nuklear looks like a good abstraction, you can draw without using GL calls. The documentation is just a bit longer than it is acceptable in 2017, but otherwise no problems with hiding backends away.

> tried it and is too limited in what you can do with it in terms of GUI styles.

Demo screenshots are telling the opposite. And the lack of complex widgets like table is not a problem of a lacking GUI styles. In terms of style, you can paint the components as you like. Even QtQuick is a bit harder in that matter (i.e. style customisation).

`</off-topic>`

**Comment by joeblew99** [comment]
thanks @xlab 

Will pick this up over at your repo
