### ISSUE TITLE
TextEditor, print "squares" if press some keys.

### ISSUE THREAD

**Issue by waltrapa** [aarzilli/nucular#41]
Fixed extra chars in #39 but if press any of keys :
- "Alt Gr."
- "block uppercase"
- "numerical block"
- Any operation symbol key "+ - * /" in numerical block

TextEditor, print a "square".

Thank you again.

_Originally posted by @waltrapa in https://github.com/aarzilli/nucular/issues/39#issuecomment-487322994_

**Comment by waltrapa** [comment]
Print "squares" is fixed, but in Spanish key layer:

- Alt Gr extra chars is not accessible, for example atlGr+2 print "2" and not "@". Same for access to Backward Slash (maybe ASCI code 92), "#", "€", "|" chars.
- Upper Caps + ñ print "N" and not "Ñ"

Thank you very much again.

**Comment by dennwc** [comment]
Same happens on other keyboard locales as well. It prints English, but everything else ends up as Unicode replacement characters (squares).

**Comment by aarzilli** [comment]
I'm aware that anything that's accessed through alt-gr won't work, it would require xkb support to work and I don't plan to do that anytime soon.

> Upper Caps + ñ print "N" and not "Ñ"

I tested that and it works. Both shift-ñ and capslock,ñ print Ñ with a spanish layout (es). You'll have to be more specific on the circumstances.

>Same happens on other keyboard locales as well. It prints English, but everything else ends up as Unicode replacement characters (squares).

I'm pretty sure that it works with all of the latin-1 block at least and I expect it to work with the majority of unicode, you'll have to be more specific on what doesn't work.

**Comment by waltrapa** [comment]
Sorry, is my fault.

func updatefn(w *nucular.Window) {
        w.Row(20).Dynamic(1)
        FieldEditor.Edit(w)
}

The font exceeds the height. Change to w.Row(26).Dynamic(1) draw full char.
