### ISSUE TITLE
freebsd build?

### ISSUE THREAD

**Issue by l0k18** [aarzilli/nucular#49]
As I understand it, this library has only one non-Go dependency, indirectly for GLFW. In our dev shop we have been doing a lot of testing of multi-platform GL based GUI frameworks and for Go this one is the best, but my colleague runs FreeBSD (12) and it looks like the only reason it can't be built on freebsd is because of build tags. I'm not sure where to start looking for how to fix it.

First error we get is the NewMasterWindowSize is undefined, and going to the shiny.go file that declares it, it's possible to see it has a complicated set of build tags that must be excluding it. We removed them, and other things too. 

If we get it working we should probably make a pull request.

**Comment by aarzilli** [comment]
With 4adff27 it should build with GOOS=freebsd.
