### ISSUE TITLE
GUI _demo stalls on OSX

### ISSUE THREAD

**Issue by ghost** [aarzilli/nucular#5]
the GUI stalls on OSX as soon as its opened. This results in the beachball from hell.

I dont have time to look into whats going on. Am away, but wanted to raise this.

**Comment by paulhovey** [comment]
The demo works fine for me on OS X 10.12.3 .  What version of Golang do you have installed?  I was experiencing a spinning beachball of death trying out https://github.com/golang-ui/nuklear with go v1.5 , but upgrading to the latest golang (v1.7.5) seemed to fix the issue.

**Comment by ghost** [comment]
O am using 1.7.
Will upgrade and try now

**Comment by joeblew99** [comment]
Am back from holidays, and gave it another go.

in the demo.go file i set the following so it runs the most basic demo and i still get the beachball :)
```
var whichdemo int = 5
````

If i never touch the mouse, the beach ball does not start.

Also gdlv works fine for me.  So it seems that there is something about the demo code particularly.. 


![screen shot 2017-02-18 at 00 13 17](https://cloud.githubusercontent.com/assets/11999859/23086727/1bbaa2f8-f56f-11e6-8d15-baae99099834.png)




here is my environment:
```
x-MacBook-Pro:_demo apple$ pwd
/Users/apple/workspace/go/src/github.com/aarzilli/nucular/_demo
x-MacBook-Pro:_demo apple$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
x-MacBook-Pro:_demo apple$ go version
go version go1.8 darwin/amd64
x-MacBook-Pro:_demo apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build072332625=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
x-MacBook-Pro:_demo apple$ 

```

**Comment by paulhovey** [comment]
I tested with `var whichdemo int = 5` and am able to move the mouse fine:

![image](https://cloud.githubusercontent.com/assets/635145/23094349/35eb58f6-f5c5-11e6-8468-a53315d2b0a0.png)

My environment:

`Pauls-MacBook-Pro:_demo paulhovey$ pwd
/Users/paulhovey/Documents/Development/go/src/github.com/aarzilli/nucular/_demo
Pauls-MacBook-Pro:_demo paulhovey$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
Pauls-MacBook-Pro:_demo paulhovey$ go version
go version go1.7.5 darwin/amd64
Pauls-MacBook-Pro:_demo paulhovey$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/paulhovey/Documents/Development/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9z/8pj46n054nd3rpv88xrq3nnr0000gn/T/go-build467255416=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"`

**Comment by ghost** [comment]
working for me. I am not sure what it was, but all good now.
