### ISSUE TITLE
How to increase font size for specified UI control?

### ISSUE THREAD

**Issue by AllenDang** [aarzilli/nucular#52]
Can I change font size just for specified UI control?

I expect the API should work like this:

```
func updatefn(w *nucular.Window) {
    w.PushFont(font)
    w.Label("Big Hello", "LC")
    w.PopFont(font)
}
```

I cannot find related api for that, or is there any work around?

**Comment by AllenDang** [comment]
I found out that MasterWindows.Style().Scale() might do the trick, it does create a bigger label, but then I found it will reset the font I just loaded to default.

Here is the sample code:

```
func updatefn(w *nucular.Window) {
        // Try to create a bigger label
	style := w.Master().Style()
	style.Scale(2)
	w.Label(currentEvent.EventName, "LC")
	style.Scale(1)
}

func main() {
        ...
	fontPath := "/Library/Fonts/Microsoft/SimHei.ttf"
	if fileExists(fontPath) {
		fontData, _ := ioutil.ReadFile(fontPath)
		normalFont, _ := font.NewFace(fontData, 12)
		style.Font = normalFont
	}

	wnd.SetStyle(style)
}
```
As you can see, I loaded a chinese font at start, but after the bigger label is created, the font will be set to default font, which mess all the chinese characters.

**Comment by aarzilli** [comment]
Just change the font to the alternate one, do what you have to do and then change it back.

```
temp := style.Font
style.Font = biggerFont
w.Label(...)
style.Font = temp
```

**Comment by olarriga** [comment]
If someone is searching about the same think, here is the solution I found to change the font size for a specific Label :

	st := style.FromTheme(style.DarkTheme, 2.0)
	st.Font = font.DefaultFont(6, 2.0)
	w.Master().SetStyle(st)
	w.Label("Small text", "CT")
	w.Master().SetStyle(style.FromTheme(style.DarkTheme, 2.0))
