### ISSUE TITLE
Input events for "active" Window?

### ISSUE THREAD

**Issue by justinfx** [aarzilli/nucular#53]
I've been trying to figure out how to solve a problem when handling inputs between 2 `GroupList` items, within two different `Group` windows of the master window. I had assumed (maybe incorrectly) that the `Window.Input()` is scoped to that particular window, but it seems that when I copy the demo example of handling up/down arrows for the list navigation, both lists in the different windows see the input and navigate.

Is there a particular pattern for handling the input events of the "active" window with focus? I tried to see if this was a Nuklear concept and came across this issue: https://github.com/vurtun/nuklear/issues/107
Seems that `nk_item_any_active()` was added as a way to determine if a given window has the active focus. Is there something like this in nucular?

Thanks for this cool GUI framework.

**Comment by justinfx** [comment]
For now I have had to manually track a focus state with something like this:

```go
type Focusable interface {
	HasFocus() bool
	SetFocus(bool)
}

type MainApp struct {
        // ...
	focusables []Focusable
}

func (a *MainApp) setFocus(w Focusable) {
	for _, f := range a.focusables {
		f.SetFocus(f == w)
	}
}
```

And then the widgets implementing `Focusable` have to do this:

```go
if input := win.Input(); input != nil && w.HasFocus() {
    // ...
```

**Comment by aarzilli** [comment]
Input is indeed scoped to the particular window you're calling it on but scope is only tracked for "real" windows (the master window, popups, non-modal windows...) not for windows made with GroupBegin/GroupEnd.

There are two ways to do this: the first one is to implement focus-follows-mouse by calling KeyboardOnHover.

The second one is to track focus, I've been doing this by keeping a flag for each thing that can be focused and if any button was clicked check if it's inside the bounds of the focusable widget and set the flag accordingly.

**Comment by justinfx** [comment]
Thanks for clarifying! I will check out the follow mouse approach. I've been using a rough version of what you suggested for manually tracking the focus widget.
