### ISSUE TITLE
TextEditor doesn't support Chinese character.

### ISSUE THREAD

**Issue by AllenDang** [aarzilli/nucular#55]
I loaded the chinese font and set it to style.Font, display only widgets (e.g. Label, ButtonText, etc...) works fine, but TextEditor seems doesn't support do neither display or input Chinese characters.

I set the flags of TextEditor to nucular.EditField.

For input, after I switched my system input method to Chinese PinYin, every key strokes will input directly as English character.

For copy-paste, all Chinese characters will be shown as square like below.

Here shows how it looks like:
![截屏2019-12-10下午10 00 23](https://user-images.githubusercontent.com/18550/70535723-847d3b00-1b98-11ea-98cf-b1fe51bbf650.png)

My OS is MacOS v10.15.1, go version 1.13.4, nucular is latest from main branch.

**Comment by aarzilli** [comment]
I'll try to get to this but I don't know when I will have the time.

**Comment by AllenDang** [comment]
@aarzilli I found the copy-paste issue is caused by pbpaste. In MacOS it will not return UTF-8 by default.
If I add the env variable LANG=en_US.UTF-8 to the command, it works.

So patch will be in cliboard_darwin.go line 20

```
func getPasteCommand() *exec.Cmd {
	cmd := exec.Command(pasteCmdArgs)
        cmd.Env = []string{"LANG=en_US.UTF-8"}
        return cmd
}
```

But I thought it might not be a good solution. Gioui should provide clipboard related functions to ease the OS differences.

**Comment by aarzilli** [comment]
Thank you
