### ISSUE TITLE
Crash on text reflow

### ISSUE THREAD

**Issue by leandrosansilva** [aarzilli/nucular#67]
Hi,

I've been able to consistently reproduce this issue when using gdlv on linux. It happens on both gio and shinny backends).

Unfortunately I could not reduce it to a basic example, as it happens only when I debug a program [1] with some very specific input data which I cannot make available.

I've just `go install`'ed `gdlv@master` as of today (2022-04-28).

This is the backtrace I get on panic, when gdlv crashes:

```
panic: runtime error: index out of range [894179] with length 894179

goroutine 39 [running]:
github.com/aarzilli/nucular/richtext.(*RichText).reflow(0xc000226280)
        /home/tenchi/.go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20220225092833-916d8e586506/richtext/draw.go:465 +0xcb5
github.com/aarzilli/nucular/richtext.(*RichText).Tail(0xc000226280, 0x0?)
        /home/tenchi/.go/pkg/mod/github.com/aarzilli/nucular@v0.0.0-20220225092833-916d8e586506/richtext/rtxt.go:394 +0x172
main.(*editorWriter).Write(0xc00020a098?, {0xc00016c000, 0x484, 0x7f792eb3f5b8?})
        /home/tenchi/.go/pkg/mod/github.com/aarzilli/gdlv@v1.7.1-0.20220406065830-978c57b40f1b/scrollback.go:48 +0x4e6
io.copyBuffer({0x9ea320, 0xc0001602b8}, {0x9ea4c0, 0xc00020a098}, {0x0, 0x0, 0x0})
        /usr/lib/go/src/io/io.go:428 +0x204
io.Copy(...)
        /usr/lib/go/src/io/io.go:385
main.(*ServerDescr).stderrProcess(0xcf9520)
        /home/tenchi/.go/pkg/mod/github.com/aarzilli/gdlv@v1.7.1-0.20220406065830-978c57b40f1b/server.go:344 +0x70
created by main.(*ServerDescr).Rebuild
        /home/tenchi/.go/pkg/mod/github.com/aarzilli/gdlv@v1.7.1-0.20220406065830-978c57b40f1b/server.go:395 +0x47c

```

I might try to debug it myself and fix it, but I confess I'm not used to nucular codebase, so any directions on testing/debugging/fixing it will help :-)

[1] https://gitlab.com/lightmeter/controlcenter

**Comment by aarzilli** [comment]
Thank you, reopen the issue if this didn't fix the problem.

**Comment by leandrosansilva** [comment]
I can confirm that the issue was fixed. I recompiled gdlv using the latest `nucular@master` and I don't experience the issue anymore.

Thank you a lot!
