### ISSUE TITLE
Maximized Windows Are Stuck In The Background

### ISSUE THREAD

**Issue by justledbetter** [aarzilli/nucular#86]
When a user drags any popup window to the top to maximize the window, it is pinned behind all other popup windows in the view.  Is this expected (or am I doing something wrong)?

```
package main

import (
        "image"

        "github.com/aarzilli/nucular"
        "github.com/aarzilli/nucular/rect"
        "github.com/aarzilli/nucular/style"
)

func subwindowUpdate(w *nucular.Window) {
        w.Row(0).Dynamic(1)
        w.Label("Maximize one of these windows\n(it will be stuck at the back of the stack)", "LC")
}

func main() {
        w := nucular.NewMasterWindowSize(
                nucular.WindowScalable,
                "Test window",
                image.Point{640, 480},
                func(w *nucular.Window) {
                        w.Row(0).Dynamic(1)
                },
        )
        w.SetStyle(style.FromTheme(style.WhiteTheme, 1.0))
        for i := 0; i < 3; i++ {
                w.PopupOpen(
                        "Sub Window",
                        nucular.WindowNonmodal|nucular.WindowMovable|nucular.WindowScalable|
                                nucular.WindowTitle|nucular.WindowBorder|nucular.WindowClosable,
                        rect.Rect{X: 50 + 10*i, Y: 50 + 10*i, W: 400, H: 100},
                        false,
                        subwindowUpdate,
                )
        }
        w.Main()
}
```

**Comment by aarzilli** [comment]
There is no maximization feature. When you drag a window to the top what happens is that it gets docked. In this state it is expected to be behind every other popup window.

**Comment by justledbetter** [comment]
Ah okay, apologies for the misunderstanding.

There are situations where I'd like to be able to "maximize" a popup window (make it the exclusive focus for the user to work in, at their discretion).  Any suggestions on the best way to implement that?  (Happy to try and implement it on this end first to see if it works)

**Comment by aarzilli** [comment]
If you don't care about resizes, it's just `w.Bounds = rootWin.Bounds`.

**Comment by justledbetter** [comment]
Ah, interesting.  I can bind a keyboard shortcut to do that easily enough.  Will see if the users think that's good enough for now - Thanks!
