### ISSUE TITLE
gomobile build 

### ISSUE THREAD

**Issue by joeblew99** [aarzilli/nucular#9]
Are you interested in getting this going on mobile ?

I made a simple copy of your demo and tried to get it going on mobile.
Because you use mobile/gl, it is capable to work.

But it needs to import golang.org/x/mobile/app, and i am not sure where due to the way the code is composed.
Everything else works from what i can see :)

main.go. This just calls the standard overview.go demo
````
package main

import (
	"github.com/aarzilli/nucular"
	nstyle "github.com/aarzilli/nucular/style"
)

const scaling = 1.8

//var theme nucular.Theme = nucular.WhiteTheme
var theme nstyle.Theme = nstyle.DarkTheme

func main() {
	var wnd nucular.MasterWindow

	od := newOverviewDemo()
	od.Theme = theme
	wnd = nucular.NewMasterWindow(0, "Overview", od.overviewDemo)

	wnd.SetStyle(nstyle.FromTheme(theme, scaling))
	wnd.Main()

}


````

````
gomobile install -target=android .
# gomobile: /nucular/demo2 does not import "golang.org/x/mobile/app"
````

**Comment by aarzilli** [comment]
> Because you use mobile/gl, it is capable to work.
AFAIK shiny doesn't support android.
